apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-devops-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-devops-app
  template:
    metadata:
      labels:
        app: my-devops-app
    spec:
      containers:
      - name: my-devops-app
        image: 618642321171.dkr.ecr.us-east-1.amazonaws.com/my-devops-app:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-devops-app-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: my-devops-app
  ports:
  - port: 80
    targetPort: 80